#!usr/bin/python

a = input("a =")
b = input("b =")
print ('Tong 2 so a va b: ') 
print (a+b)
print ('Hieu 2 so a va b: ') 
print (a-b)
print ('Tich 2 so a va b: ') 
print (a*b)
print ('Thuong 2 so a va b: ') 
print (float(a)/b)
print ('Chia 2 so a va b: ')
print (a%b)
print ('Luy thua a va b: ')
print (a**b)
